# GitHub Actions Workflow para Azure App Service

name: Build and deploy ASP.Net Core app to Azure Web App - agilityfeatdemoapi

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # Requerido para actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'  # Ajusta según tu versión

      - name: Restore dependencies
        run: dotnet restore Backend.sln

      - name: Build with dotnet
        run: dotnet build Backend.sln --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish Backend.sln -c Release -o "${{env.DOTNET_ROOT}}/myapp" --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Requerido para solicitar el JWT
      contents: read # Requerido para actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7D8E6F14897540D3840D241FF39A5DD8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_835DB0C520CB42CB8783F0065B351206 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D5FF03CBBF654EF2936023CBBBB339AA }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'agilityfeatdemoapi'
          slot-name: 'Production'
          package: .
